language: node_js

node_js:
  - "12"
  
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/regnum_tests

before_script:
  - psql -c 'create database  regnum_tests;' -U postgres
  - psql -U postgres -d regnum_tests -a -f tables.sql

services:
  - postgresql